### ISSUE TITLE
Alias/Anchors do not work across includes

### ISSUE THREAD

**Issue by robbecker-wf** [dart-lang/yaml#105]
I'm not sure if this is something that should work and is a bug or not, but it could be handy. I would like to have an included yaml file at the top that defines some aliases for use later. 

Here's an example:

**abilities.yaml**
```yaml
# Define aliases for different abilities that are actually numbers and not strings
abilities:
  fly: &ability_fly 1
  swim: &ability_swim 2
  walk: &ability_walk 3
```

**creatures.yaml**
```yaml
include: abilities.yaml
# I'd like the aliases defined in the included file to exist here

creatures:
  bat:
    abilities:
      - *ability_fly  # These don't seem to be in scope
  fish:
    abilities:
      - *ability_swim # These don't seem to be in scope
  human:
    abilities:
      - *ability_swim # These don't seem to be in scope
      - *ability_walk # These don't seem to be in scope
```

I've verified that the alias and anchor format is correct and this works if the 2 files are combined into 1 and  there is no include. It appears that maybe `include` is a Dart specific addition to yaml and not in the spec? Does that mean this request could be added?
