### ISSUE TITLE
loadYaml in dart takes 200-300ms on android

### ISSUE THREAD

**Issue by ksimbili** [dart-lang/yaml#12]
16:35:57.902 load yaml
```
verb: RecommendCafes
recipe:
  - verb: List
    outputs: ["Cafe[]"]
  - verb: Fetch
    inputs: ["Cafe[]"]
    outputs: ["CafeWithMenu[]"]
  - verb: Flatten
    inputs: ["CafeWithMenu[]"]
    outputs: ["DishOffering[]"]
  - verb: Score
    inputs: ["DishOffering[]"]
    outputs: ["DishOffering[]/Scored"]
  - verb: Display
    inputs: ["DishOffering[]/Scored"]
```
16:35:58.203 load yaml done
