### ISSUE TITLE
Yaml Loader._loadAlias  failed for ` - **.g.dart`

### ISSUE THREAD

**Issue by LongXiangGuo** [dart-lang/yaml#149]
```
include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - **.g.dart

  errors:
    use_build_context_synchronously: ignore
```

<details>

```

4 │     - **.g.dart
  │       ^^^^^^^^^
  ╵ 
#0      Loader._loadAlias (package:yaml/src/loader.dart:114:5)
#1      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#2      Loader._loadSequence (package:yaml/src/loader.dart:146:20)
#3      Loader._loadNode (package:yaml/src/loader.dart:90:16)
#4      Loader._loadMapping (package:yaml/src/loader.dart:169:19)
#5      Loader._loadNode (package:yaml/src/loader.dart:92:16)
#6      Loader._loadMapping (package:yaml/src/loader.dart:169:19)
#7      Loader._loadNode (package:yaml/src/loader.dart:92:16)
#8      Loader._loadDocument (package:yaml/src/loader.dart:68:20)
#9      Loader.load (package:yaml/src/loader.dart:60:20)
#10     loadYamlDocument (package:yaml/yaml.dart:72:25)
#11     loadYamlNode (package:yaml/yaml.dart:57:5)
#12     loadYaml (package:yaml/yaml.dart:44:5)
#13     getExcludeFolders (file:///Users/qxz3ln7/project/tools/bin/update_analytics_options.dart:133:28)
<asynchronous suspension>
#14     main (file:///Users/qxz3ln7/project/tools/bin/update_analytics_options.dart:56:29)
<asynchronous suspension>

#0      getExcludeFolders (file:///Users/qxz3ln7/project/tools/bin/update_analytics_options.dart:142:5)
<asynchronous suspension>
#1      main (file:///Users/qxz3ln7/project/tools/bin/update_analytics_options.dart:56:29)
<asynchronous suspension>
```

</details>

**Comment by jonasfj** [comment]
This is invalid YAML.

try:
```yaml
include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - '**.g.dart'

  errors:
    use_build_context_synchronously: ignore
```
