### ISSUE TITLE
Poor error message when mixing list and key-value syntax

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/yaml#88]
Given the following input:
```yaml
linter:
  rules:
    close_sinks: false
    - empty_statements 
```
The message produced is

> Expected a key while parsing a block mapping.

While the message is technically correct, it doesn't help the author of the file figure out how to fix the issue as much as it could. A user suggested something like

> You can’t mix list and key-value syntax in the same object.

Please improve the error message for this situation.
